name: MonsterTickets
main: org.monstercraft.monsterticket.Ticket
version: 1.02
author: Fletch_to_99
description: A ticket management system.
depend: [Vault]
commands:
  request:
    description: Used to open a help ticket.
    usage: /request (description) or /help (description)
  claim:
    description: Used to claim a help ticket.
    usage: /claim (id)
  close:
    description: Used to close a ticket.
    usage: /close
  check:
    description: Used to check all tickets.
    usage: /check
  modlist:
    description: Check which mods are online.
    usage: /modlist
  mtreload:
    description: Reloads the plugins settings.
    usage: /mtreload