name: DeathExplosion
main: org.monstercraft.deathexplosion.DeathExplosion
version: 1.0
commands:
  boom:
    description: boom
    usage: /<command> [msg]
  tomb:
    description: tomb
    usage: /<command> [msg]